# Generated by Django 4.0.2 on 2023-07-23 16:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asteroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('diameter', models.FloatField()),
                ('is_hazardous', models.BooleanField()),
                ('velocity', models.FloatField()),
                ('orbiting_body', models.CharField(max_length=100)),
                ('close_approach_date', models.DateField()),
                ('miss_distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NaturalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
